name: Run ESLint on changed files
description: Run ESLint on JavaScript files
author: jackton1
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT'
    default: ${{ github.token }}
    required: true
  config-path:
    description: Eslint configuration path
    required: false
    default: '.eslintrc'
  ignore-path:
    description: Eslint ignore path
    required: false
    default: ''
  extra-args:
    description: Eslint extra arguments
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.config-path }}
    - ${{ inputs.ignore-path }}
    - ${{ inputs.extra-args }}
branding: 
  icon: check-square
  color: blue
