name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Test..."
